CREATE TABLE products (
	id SERIAL PRIMARY KEY NOT NULL,
	productname VARCHAR(30),
	manufacturer VARCHAR(30),
	eparegno VARCHAR(20),
	chemistry VARCHAR(30),
	image VARCHAR(50),
	areas VARCHAR(10),
	surfaces VARCHAR(10),
	bvclaims TEXT,
	bvkill NUMERIC,
	noroclaim BOOLEAN,
	norokill NUMERIC,
	cdiffclaim BOOLEAN,
	cdiffkill NUMERIC,
	fungiclaim BOOLEAN,
	fungikill NUMERIC,
	hmis VARCHAR(5),
	ppe VARCHAR(50),
	equipment VARCHAR(50),
	format VARCHAR(20),
	sds VARCHAR(200),
	productpage VARCHAR(200),
	techdocs VARCHAR(200),
	epamasterlabel VARCHAR(200),
	scorekill INTEGER,
	scoresafety INTEGER,
	scorepathogens INTEGER
	);
	
	
	INSERT INTO products (productname, manufacturer, eparegno, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Clorox Bleach Wipes', 'Clorox', '67619-12', 'sodium hypochlorite (bleach)', 'high', 'hard', 'Adenoviros type 2, Avian Influenza A virus, Human Coronavirus, Hepatitis A virus (HAV), Hepatitis B virus (HBV), Hepatitis C virus (HCV), Herpes Simplex virus type 2, HIV type 1, Influenza A virus, Norovirus, Poliovirus type 1, Rhinovirus, Rotavirus, RSV, Acinetobacter baumannii, Bortedella pertussis, Campylobacter jejuni, Enterobacter aerogenes, Enterobacter cloacae, Enterococcus faecium, VRE, Escherichia coli (E. Coli), Klebsiella pneumoniae, Legionella pneumophila, Listeria monocytogenes, CA-MRSA, Proteus mirabilis, Pseudomonas aeruginosa, Salmonella enterica, Serratia marcescens, Shigella dysentriae, Staphylococcus aureus, LRSA, MRSA, VISA, VRSA, Streptococcus pneumoniae, Streptococcus pyogenes', 1, TRUE, 1, TRUE, 3, TRUE, 3, '1/0/1', 'Eye protection, exam gloves, face mask', 'None', 'RTU Wipes', 'https://www.thecloroxcompany.com/downloads/msds/cloroxhealthcarecloroxhealthcarecloroxhealthcare/cloroxhealthcarebleachgermicidalwipesjw.pdf', 'https://www.cloroxprofessional.com/products/clorox-healthcare-bleach-germicidal-wipes/at-a-glance/', '', '', 10, 7, 10);
	
	
		INSERT INTO products (productname, manufacturer, eparegno, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Clorox HP Wipes', 'Clorox', '67619-25', 'hydrogen peroxide', 'intermed', 'hard', 'Avian Influenza A, Cytomegalovirus, Human Hepatitis B virus, Human Hepatitis C virus, Herpes Simplex virus type 1, Herpes Simplex virus type 2, HIV type 1, Human Coronavirus, Influenza A virus (H1N1), Influenza A virus / Hong Kong, Influenza B virus, Norovirus, RSV, Rhinovirus, Rotavirus, Acinetobacter baumannii, Campylobacter jejeuni, Enterobacter aerogenes, VRE, Enterococcus faecium, Escherichia coli, Klebsiella pneumoniae, Klebsiella oxytoca, Pseudomonas aeruginosa, Salmonella enterica, Staphylococcus aureus, MRSA, CA-MRSA, Stenotrophomonas maltophilia, Streptococcus pneumonia, Streptococcus pyogenes', 1, TRUE, 3, FALSE, 0, TRUE, 5, '1/0/0', 'Exam gloves', 'None', 'RTU Wipes', 'https://www.thecloroxcompany.com/downloads/msds/cloroxhealthcarecloroxhealthcarecloroxhealthcare/cloroxhealthcarehydrogenperoxidecleanerdisinfectantwipesjw2014-09-28.pdf', 'https://www.cloroxprofessional.com/products/clorox-healthcare-hydrogen-peroxide-cleaner-disinfectants/at-a-glance/', '', '', 10, 7, 10);
		
		INSERT INTO products (productname, manufacturer, eparegno, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Accel TB Wipes', 'Virox', '74559-3', 'hydrogen peroxide', 'intermed', 'hard', 'Acinetobacter baumannii, Avian Influenza H3N2, VRE, E. coli, Hepatitis B (HBV), Hepatitis C (HCV), Herpes Simplex Type 1, Herpes Simplex Type 2, HIV-1, Human Coronavirus, Influenza A Hong Kong, Poliovirus Type 1, Pseudomonas aeruginosa, Rhinovirus, Rotavirus, Salmonella enterica, Staphylococcus aureus, Staphylococcus aureus MRSA', 1, TRUE, 1, FALSE, 0, TRUE, 10, '0/0/0', 'None for routine tasks', 'None', 'RTU Wipes', 'http://unimedcorp.com/MSDS/SDS_AccelTBWipes.pdf', 'http://viroxhealthcare.com/?page=accel-wipes', '', '', 10, 10, 7);
	
INSERT INTO products (productname, manufacturer, eparegno, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Cavicide', 'Metrex', '46781-6', 'quat/alcohol', 'intermed', 'hard', 'Mycobacterium tuberculosis (TB), Staphylococcus aureus, Pseudomonas aeruginosa, Salmonella enterica, Trichophyton mentagrophytes, Methicillin Resistant Staphylococcus aureus (MRSA), VRE,  Hepatitis B Virus (HBV), Hepatitis C Virus (HCV), Herpes Simplex Virus Type 1, Herpes Simplex Virus Type 2, HIV-1, Human Coronavirus (not associated with SARS), Influenza A2 Virus', 3, FALSE, 0, FALSE, 0, TRUE, 3, '2/3/0', 'Eye protection, exam gloves', 'None', 'RTU Liquid', 'http://www.metrex.com/sites/default/files/content/education-file/education-file-upload/CaviCide%20US%20GHS%20SDS%20(3.23.16).pdf', 'http://www.metrex.com/products/surface-disinfectants/cavicide#features-and-benefits', 'http://www.metrex.com/sites/default/files/content/education-file/education-file-upload/cavicide_technical-bulletin-us-en.pdf', 'https://www3.epa.gov/pesticides/chem_search/ppls/046781-00006-20110918.pdf', 8, 4, 5);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('CaviWipes', 'Metrex', '46781-8','caviwipes.jpg', 'quat/alcohol', 'intermed', 'hard', 'Mycobacterium tuberculosis (TB), Staphylococcus aureus, Pseudomonas aeruginosa, Salmonella enterica, Trichophyton mentagrophytes, Methicillin Resistant Staphylococcus aureus (MRSA), VRE,  Hepatitis B Virus (HBV), Hepatitis C Virus (HCV), Herpes Simplex Virus Type 1, Herpes Simplex Virus Type 2, HIV-1, Influenza A2 Virus', 3, FALSE, 0, FALSE, 0, TRUE, 3, '2/3/0', 'Eye protection, exam gloves', 'None', 'RTU Wipes', 'http://www.metrex.com/sites/default/files/content/education-file/education-file-upload/CaviWipes%20US%20GHS%20SDS%20(3.23.2016).pdf', 'http://www.metrex.com/products/surface-disinfectants/caviwipes', 'http://www.metrex.com/sites/default/files/content/education-file/education-file-upload/caviwipes-caviwipesxl-technical-bulletin-us-en.pdf', 'https://www3.epa.gov/pesticides/chem_search/ppls/046781-00008-20150306.pdf', 8, 4, 5);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('CaviCide1', 'Metrex', '46781-12','cavicide1.jpg', 'quat/alcohol', 'intermed', 'hard', 'Mycobacterium tuberculosis (TB), Staphylococcus aureus, Pseudomonas aeruginosa, Salmonella enterica, Trichophyton mentagrophytes, Candida albicans, Acinetobacter baumannii, Klebsiella pneumoniae, Bordetella pertussis, MRSA, MRSE, VRE, VISA, Escherichia coli, Hepatitis B Virus (HBV), Hepatitis C Virus (HCV), Herpes Simplex Virus Type 1, Herpes Simplex Virus Type 2, HIV-1, Human Coronavirus (not associated with SARS), Feline Calicivirus, Norovirus, Rotavirus, Influenza A, H3N2 Virus', 1, TRUE, 1, FALSE, 0, TRUE, 1, 'none', 'Eye protection, exam gloves', 'None', 'RTU Liquid', 'http://www.metrex.com/sites/default/files/content/education-file/education-file-upload/CaviCide1%20US%20GHS%20SDS%20(3.23.16).pdf', 'http://www.metrex.com/products/surface-disinfectants/cavicide1', 'http://www.metrex.com/sites/default/files/content/education-file/education-file-upload/cavicide1-technical-bulletin-us-en.pdf', 'https://www3.epa.gov/pesticides/chem_search/ppls/046781-00012-20120419.pdf', 10, 4, 7);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('CaviWipes1', 'Metrex', '46781-13','CaviWipes1.jpg', 'quat/alcohol', 'intermed', 'hard', 'Mycobacterium tuberculosis (TB), Staphylococcus aureus, Pseudomonas aeruginosa, Salmonella enterica, Trichophyton mentagrophytes, Candida albicans, Acinetobacter baumannii, Klebsiella pneumoniae, Bordetella pertussis, MRSA, MRSE, VRE, VISA, Escherichia coli, Hepatitis B Virus (HBV),  Hepatitis C Virus (HCV), Herpes Simplex Virus Type 1, Herpes Simplex Virus Type 2, HIV-1, Human Coronavirus (not associated with SARS), Influenza A, H3N2 Virus', 1, FALSE, 0, FALSE, 0, TRUE, 1, 'none', 'Eye protection, exam gloves', 'None', 'RTU Wipes', 'http://www.metrex.com/sites/default/files/content/education-file/education-file-upload/CaviWipes1%20US%20GHS%20SDS%20(3.23.2016).pdf', 'http://www.metrex.com/products/surface-disinfectants/caviwipes1', 'http://www.metrex.com/sites/default/files/content/education-file/education-file-upload/caviwipes1-technical-bulletin-us-en-10-22-2014.pdf', 'https://www3.epa.gov/pesticides/chem_search/ppls/046781-00013-20160519.pdf', 10, 4, 8);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('CaviCide AF', 'Metrex', '1839-225-46781','CaviCideAF.jpg', 'quat', 'intermed', 'hard', 'Mycobacterium bovis (TB), Pseudomonas aeruginosa, MRSA, E. coli, Streptococcus pyogenes, Listeria monocytogenes, Yersinia enterocolitica, Corynebacterium ammoniagenes, Salmonella enterica, VRE, Staphylococcus aureus, MRSE, CA-MRSA, Human Coronavirus, SARS-associated Coronavirus, Avian Influenza A virus strain H3N2, Avian Influenza A virus strain H9N2, Influenza A (H1N1) Virus, Paramyxovirus (Mumps), Rhinovirus, Rotavirus, HIV-1, Norovirus, Feline Calicivirus, Rabies Virus', 3, TRUE, 0.5, FALSE, 0, FALSE, 0, 'none', 'Eye protection, exam gloves', 'None', 'RTU Liquid', 'http://www.metrex.com/sites/default/files/content/education-file/education-file-upload/CaviCide%20AF%20GHS%20SDS%20Final.pdf', 'http://www.metrex.com/products/surface-disinfectants/cavicide-af', 'http://www.metrex.com/sites/default/files/content/education-file/education-file-upload/MKT-1172%20CaviCide%20AF%20Technical%20Bulletin_20150929.pdf', 'https://www3.epa.gov/pesticides/chem_search/ppls/001839-00225-20110106.pdf', 8, 7, 7);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Sani-Cloth Bleach Wipes', 'PDI', '9480-8','saniclothbleachwipe.png', 'sodium hypochlorite (bleach)', 'high', 'hard', 'Bordetella pertussis, Burkholderia cepacia, Campylobacter jejuni, Escherichia coli, Klebsiella pneumoniae,  Legionella pneumophila, Listeria monocytogenes, Pseudomonas aeruginosa, Salmonella enterica, Serratia marcescens, Staphylococcus aureus, Streptococcus pyogenes, Acinetobacter baumannii, Enterobacter cloacae, Escherichia coli, Klebsiella pneumoniae, CA-MRSA, MRSA, Streptococcus pneumoniae, VISA, VRSA, VRE, Avian Influenza A H5N1 virus, Cytomegalovirus, Herpes simplex virus type 2, Human Coronavirus, Influenza A virus /Hong Kong Strain, Influenza B virus, RSV, Adenovirus type 2, Canine Parvovirus, Hepatitis A virus  (HAV), Norovirus, Poliovirus, Rhinovirus, Rotavirus, Hepatitis B virus (HBV), Hepatitis C virus (HCV) Bovine Diarrhea Virus, HIV-1 (AIDS virus), Aspergillus brasiliensis, Candida albicans, Trichophyton mentagrophytes, Clostridium difficile spores', 1, TRUE, 1, TRUE, 4, TRUE, 4, '1/1/0', 'Eye protection, exam gloves, face mask', 'None', 'RTU Wipes', 'http://pdihc.com/sites/default/files/73bbedd76aa896857c5cd65b507943bc.pdf', 'http://pdihc.com/content/sani-cloth%C2%AE-bleach', '', 'https://www3.epa.gov/pesticides/chem_search/ppls/009480-00008-20130716.pdf', 10, 7, 10);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Sani-Cloth AF3 Wipes', 'PDI', '9480-9','saniclothaf3.png', 'quat', 'intermed', 'hard', 'Bordetella bronchiseptica, Bordetella pertussis, Burkholderia cepacia, Campylobacter jejuni, Enterobacter aerogenes,  Escherichia coli, Klebsiella pneumoniae,  Listeria monocytogenes, Proteus vulgaris, Pseudomonas aeruginosa, Salmonella enterica, Serratia marcescens, Shigella dysenteriae, Staphylococcus aureus, Streptococcus pyogenes, Vibrio cholera, Yersinia enterocolitica, Acinetobacter baumannii, CA-MRSA, MRSA,  Streptococcus pneumoniae, VRSA, VRE, Avian Influenza A H5N1 virus, Cytomegalovirus, Herpes simplex virus type 2, Human Coronavirus, Influenza A virus/Hong Kong, Pandemic 2009 H1N1 influenza A virus, Influenza B virus, RSV,  Rotavirus, Hepatitis B virus (HBV), Hepatitis C virus (HCV),  HIV-1 (AIDS virus),', 3, FALSE, 0, FALSE, 0, TRUE, 3, '2/0/0', 'Exam gloves', 'None', 'RTU Wipes', 'http://pdihc.com/sites/default/files/SaniClothAF3SDSEnglish.pdf', 'http://pdihc.com/all-products/sani-cloth%C2%AE-af3', 'http://pdihc.com/sites/default/files/f8b79134a2baab9c20550eab22c1be4a.pdf', '', 8, 4, 10);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Super Sani-Cloth Wipes', 'PDI', '9480-4 ','supersanicloth.png', 'quat/alcohol', 'intermed', 'hard', 'Acinetobacter baumannii, Enterobacter cloacae, Escherichia coli (E. coli), Klebsiella pneumoniae, MRSA,  VRE, Bordetella pertussis, Burkholderia cepacia, Campylobacter jejuni, Escherichia coli (E. coli), Pseudomonas aeruginosa, Salmonella enterica, Staphylococcus aureus, Mycobacterium bovis (TB), Herpes Simplex type 2 virus, Human Coronavirus, Influenza A virus/Hong Kong, Pandemic 2009 H1N1 Influenza A virus, Influenza A (H1N1) virus, Vaccinia virus, RSV, Adenovirus, Rhinovirus, Rotavirus, Hepatitis B virus (HBV), Hepatitis C virus (HCV), HIV-1 (AIDS virus), Candida albicans', 2, FALSE, 0, FALSE, 0, FALSE, 0, '2/3/0', 'Eye protection, exam gloves, face mask', 'None', 'RTU Wipes', 'http://pdihc.com/sites/default/files/966b322087d48685dcb3ffa38712b578.pdf', 'http://pdihc.com/content/super-sani-cloth%C2%AE', 'http://pdihc.com/sites/default/files/77fd3798ce1162b368e48dcd1ff80302.pdf', '', 9, 4, 10);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Oxivir TB Liquid', 'Diversey', '70627-56','oxivirtb.jpg', 'hydrogen peroxide', 'intermed', 'both', 'Staphylococcus aureus, Salmonella Enterich, Pseudomonas aeruginosa, Acinetobacter baumannii, Escherichia coli, Klebsiella pneumoniae, Shigella dysenteriae, VRE, MRSA, CA-MRSA, Adenovirus, Hepatitis B (HBV), Hepatitis C (HCV), Herpes Simplex virus type 1, Herpes Simplex virus type 2, HIV-1 (AIDS virus), Human Coronavirus, Influenza A Hong Kong, Norovirus, Poliovirus, Rhinovirus, Rotavirus, Avian Influenza A, Mycobacterium bovis (TB), Trichophyton mentagrophytes', 1, TRUE, 1, FALSE, 0, TRUE, 5, '0/0/0', 'None for routine tasks', 'None', 'RTU Liquid', 'https://sds.sealedair.com/private/document.aspx?prd=MS0800255~~PDF~~MTR~~ANGH~~EN~~&_ga=1.209068178.120435454.1467725938', 'https://sealedair.com/diversey-care/diversey-care-products/oxivir-tb', '', 'https://www3.epa.gov/pesticides/chem_search/ppls/070627-00056-20141209.pdf', 10, 10, 7);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Oxivir TB Wipes', 'Diversey', '70627-60','oxivirtbwipes.jpg', 'hydrogen peroxide', 'intermed', 'hard', 'Staphylococcus aureus, Acinetobacter baumannii, Klebsiella pneumoniae, Salmonella enterica, Escherichia coli, Shigella dysenteriae, Pseudomonas aeruginosa, VRE, CA-MRSA, MRSA,  Adenovirus ,Herpes Simplex Virus Type 2, Norovirus, Hepatitis B Virus (HBV), HIV-1 (AIDS Virus), Poliovirus, Hepatitis C Virus (HCV), Human Coronavirus, Rhinovirus, Herpes Simplex Virus Type 1 (HSV-1), Influenza A/Hong Kong, Rotavirus, Avian Influenza A (H3N2), Mycobacterium bovis (TB),  Trichophyton mentagrophytes', 1, TRUE, 1, FALSE, 0, TRUE, 10, '0/0/0', 'None for routine tasks', 'None', 'RTU Wipes', 'https://sds.sealedair.com/private/document.aspx?prd=MS0800545~~PDF~~MTR~~ANGH~~EN~~&_ga=1.83184662.120435454.1467725938', 'https://sealedair.com/diversey-care/diversey-care-products/oxivir-tb-wipes', '', 'https://www3.epa.gov/pesticides/chem_search/ppls/070627-00060-20150729.pdf', 10, 10, 7);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Oxivir Five 16 Liquid', 'Diversey', '70627-58','oxivirfive16.jpg', 'hydrogen peroxide', 'low', 'hard', 'Pseudomonas aeruginosa, Salmonella enterica, Staphylococcus aureus, Acinetobacter baumannii, Escherichia coli, Klebsiella pneumoniae, Usteria monocytogenes, Shigella dysenteriae, Streptococcus pyogenes, VRE, CA-MRSA, MRSE, MRSA, Streptococcus pneumoniae, Avian Influenza A Virus, Trichophyton mentagrophytes, Adenovirus, Herpes Simplex Virus Type 2, Human Coronavirus,  Influenza Virus Type A2 (Hong Kong), Norovirus, Parainfluenza Virus, Poliovirus, RSV, Rhinovirus, Rotavirus, Vaccinia Virus, Hepatitis B Virus (HBV), Hepatitis C Virus (HCV), HIV-1 (AIDS virus)', 5, TRUE, 5, FALSE, 0, TRUE, 10, '0/0/0', 'None for routine tasks', 'Mix bucket, measure cup or pump, water source', 'Concentrate', 'https://sealedair.com/diversey-care/diversey-care-products/oxivir-five-16-concentrate', 'https://sealedair.com/diversey-care/diversey-care-products/oxivir-five-16-concentrate', '', 'https://www3.epa.gov/pesticides/chem_search/ppls/070627-00058-20101119.pdf', 6, 10, 7);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Accel TB Liquid', 'Virox', '74559-1','AccelTBLiquid.png', 'hydrogen peroxide', 'intermed', 'both', 'Acinetobacter baumannii, Adenovirus Type 8, Avian Influenza A H3N2, VRE, E. coli, Hepatitis B (HBV), Hepatitis C (HCV), Herpes Simplex Type 1, Herpes Simplex Type 2, HIV-1, Human Coronavirus, Influenza A Hong Kong, Klebsiella pneumoniae, Poliovirus Type 1, Pseudomonas aeruginosa, Rhinovirus, Rotavirus, Salmonella enterica, Staphylococcus aureus, Staphylococcus aureus MRSA', 1, TRUE, 1, FALSE, 0, TRUE, 10, '0/0/0', 'None for routine tasks', 'None', 'RTU Liquid', 'http://unimedcorp.com/MSDS/SDS_AccelTBLiquidDisinfectant.pdf', 'http://viroxhealthcare.com/index_en.php?page=accel-rtu-liquids', '', 'https://www3.epa.gov/pesticides/chem_search/ppls/074559-00001-20151102.pdf', 10, 10, 7);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Accel TB Liquid', 'Virox', '74559-1','AccelTBLiquid.png', 'hydrogen peroxide', 'intermed', 'both', 'Acinetobacter baumannii, Adenovirus Type 8, Avian Influenza A H3N2, VRE, E. coli, Hepatitis B (HBV), Hepatitis C (HCV), Herpes Simplex Type 1, Herpes Simplex Type 2, HIV-1, Human Coronavirus, Influenza A Hong Kong, Klebsiella pneumoniae, Poliovirus Type 1, Pseudomonas aeruginosa, Rhinovirus, Rotavirus, Salmonella enterica, Staphylococcus aureus, Staphylococcus aureus MRSA', 1, TRUE, 1, FALSE, 0, TRUE, 10, '0/0/0', 'None for routine tasks', 'None', 'RTU Liquid', 'http://unimedcorp.com/MSDS/SDS_AccelTBLiquidDisinfectant.pdf', 'http://viroxhealthcare.com/index_en.php?page=accel-rtu-liquids', '', 'https://www3.epa.gov/pesticides/chem_search/ppls/074559-00001-20151102.pdf', 10, 10, 7);