CREATE TABLE products (
	id SERIAL PRIMARY KEY NOT NULL,
	productname VARCHAR(30),
	manufacturer VARCHAR(30),
	eparegno VARCHAR(20),
	chemistry VARCHAR(50),
	image VARCHAR(50),
	areas VARCHAR(10),
	surfaces VARCHAR(10),
	bvclaims TEXT,
	bvkill NUMERIC,
	noroclaim BOOLEAN,
	norokill NUMERIC,
	cdiffclaim BOOLEAN,
	cdiffkill NUMERIC,
	fungiclaim BOOLEAN,
	fungikill NUMERIC,
	hmis VARCHAR(5),
	ppe VARCHAR(50),
	equipment VARCHAR(50),
	format VARCHAR(20),
	sds VARCHAR(300),
	productpage VARCHAR(300),
	techdocs VARCHAR(300),
	epamasterlabel VARCHAR(300),
	scorekill INTEGER,
	scoresafety INTEGER,
	scorepathogens INTEGER
	);


	INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Clorox Bleach Wipes', 'Clorox', '67619-12', 'disinfectantimages/cloroxbleachwipes.png', 'sodium hypochlorite (bleach)', 'high', 'hard', 'Adenoviros type 2, Avian Influenza A virus, Human Coronavirus, Hepatitis A virus (HAV), Hepatitis B virus (HBV), Hepatitis C virus (HCV), Herpes Simplex virus type 2, HIV type 1, Influenza A virus, Norovirus, Poliovirus type 1, Rhinovirus, Rotavirus, RSV, Acinetobacter baumannii, Bortedella pertussis, Campylobacter jejuni, Enterobacter aerogenes, Enterobacter cloacae, Enterococcus faecium, VRE, Escherichia coli (E. Coli), Klebsiella pneumoniae, Legionella pneumophila, Listeria monocytogenes, CA-MRSA, Proteus mirabilis, Pseudomonas aeruginosa, Salmonella enterica, Serratia marcescens, Shigella dysentriae, Staphylococcus aureus, LRSA, MRSA, VISA, VRSA, Streptococcus pneumoniae, Streptococcus pyogenes', 1, TRUE, 1, TRUE, 3, TRUE, 3, '1/0/1', 'Eye protection, exam gloves, face mask', 'None', 'RTU Wipes', 'https://www.thecloroxcompany.com/downloads/msds/cloroxhealthcarecloroxhealthcarecloroxhealthcare/cloroxhealthcarebleachgermicidalwipesjw.pdf', 'https://www.cloroxprofessional.com/products/clorox-healthcare-bleach-germicidal-wipes/at-a-glance/', '', '', 10, 7, 10);


		INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Clorox HP Wipes', 'Clorox', '67619-25', 'disinfectantimages/blorxhpwipes.png', 'hydrogen peroxide', 'intermed', 'hard', 'Avian Influenza A, Cytomegalovirus, Human Hepatitis B virus, Human Hepatitis C virus, Herpes Simplex virus type 1, Herpes Simplex virus type 2, HIV type 1, Human Coronavirus, Influenza A virus (H1N1), Influenza A virus / Hong Kong, Influenza B virus, Norovirus, RSV, Rhinovirus, Rotavirus, Acinetobacter baumannii, Campylobacter jejeuni, Enterobacter aerogenes, VRE, Enterococcus faecium, Escherichia coli, Klebsiella pneumoniae, Klebsiella oxytoca, Pseudomonas aeruginosa, Salmonella enterica, Staphylococcus aureus, MRSA, CA-MRSA, Stenotrophomonas maltophilia, Streptococcus pneumonia, Streptococcus pyogenes', 1, TRUE, 3, FALSE, 0, TRUE, 5, '1/0/0', 'Exam gloves', 'None', 'RTU Wipes', 'https://www.thecloroxcompany.com/downloads/msds/cloroxhealthcarecloroxhealthcarecloroxhealthcare/cloroxhealthcarehydrogenperoxidecleanerdisinfectantwipesjw2014-09-28.pdf', 'https://www.cloroxprofessional.com/products/clorox-healthcare-hydrogen-peroxide-cleaner-disinfectants/at-a-glance/', '', '', 10, 7, 10);

		INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Accel TB Wipes', 'Virox', '74559-3', 'disinfectantimages/AccelTBwipes.png', 'hydrogen peroxide', 'intermed', 'hard', 'Acinetobacter baumannii, Avian Influenza H3N2, VRE, E. coli, Hepatitis B (HBV), Hepatitis C (HCV), Herpes Simplex Type 1, Herpes Simplex Type 2, HIV-1, Human Coronavirus, Influenza A Hong Kong, Poliovirus Type 1, Pseudomonas aeruginosa, Rhinovirus, Rotavirus, Salmonella enterica, Staphylococcus aureus, Staphylococcus aureus MRSA', 1, TRUE, 1, FALSE, 0, TRUE, 10, '0/0/0', 'None for routine tasks', 'None', 'RTU Wipes', 'http://unimedcorp.com/MSDS/SDS_AccelTBWipes.pdf', 'http://viroxhealthcare.com/?page=accel-wipes', '', '', 10, 10, 7);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Cavicide', 'Metrex', '46781-6', 'disinfectantimages/cavicide.jpg', 'quat/alcohol', 'intermed', 'hard', 'Mycobacterium tuberculosis (TB), Staphylococcus aureus, Pseudomonas aeruginosa, Salmonella enterica, Trichophyton mentagrophytes, Methicillin Resistant Staphylococcus aureus (MRSA), VRE,  Hepatitis B Virus (HBV), Hepatitis C Virus (HCV), Herpes Simplex Virus Type 1, Herpes Simplex Virus Type 2, HIV-1, Human Coronavirus (not associated with SARS), Influenza A2 Virus', 3, FALSE, 0, FALSE, 0, TRUE, 3, '2/3/0', 'Eye protection, exam gloves', 'None', 'RTU Liquid', 'http://www.metrex.com/sites/default/files/content/education-file/education-file-upload/CaviCide%20US%20GHS%20SDS%20(3.23.16).pdf', 'http://www.metrex.com/products/surface-disinfectants/cavicide#features-and-benefits', 'http://www.metrex.com/sites/default/files/content/education-file/education-file-upload/cavicide_technical-bulletin-us-en.pdf', 'https://www3.epa.gov/pesticides/chem_search/ppls/046781-00006-20110918.pdf', 8, 4, 5);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('CaviWipes', 'Metrex', '46781-8','disinfectantimages/caviwipes.jpg', 'quat/alcohol', 'intermed', 'hard', 'Mycobacterium tuberculosis (TB), Staphylococcus aureus, Pseudomonas aeruginosa, Salmonella enterica, Trichophyton mentagrophytes, Methicillin Resistant Staphylococcus aureus (MRSA), VRE,  Hepatitis B Virus (HBV), Hepatitis C Virus (HCV), Herpes Simplex Virus Type 1, Herpes Simplex Virus Type 2, HIV-1, Influenza A2 Virus', 3, FALSE, 0, FALSE, 0, TRUE, 3, '2/3/0', 'Eye protection, exam gloves', 'None', 'RTU Wipes', 'http://www.metrex.com/sites/default/files/content/education-file/education-file-upload/CaviWipes%20US%20GHS%20SDS%20(3.23.2016).pdf', 'http://www.metrex.com/products/surface-disinfectants/caviwipes', 'http://www.metrex.com/sites/default/files/content/education-file/education-file-upload/caviwipes-caviwipesxl-technical-bulletin-us-en.pdf', 'https://www3.epa.gov/pesticides/chem_search/ppls/046781-00008-20150306.pdf', 8, 4, 5);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('CaviCide1', 'Metrex', '46781-12','disinfectantimages/cavicide1.jpg', 'quat/alcohol', 'intermed', 'hard', 'Mycobacterium tuberculosis (TB), Staphylococcus aureus, Pseudomonas aeruginosa, Salmonella enterica, Trichophyton mentagrophytes, Candida albicans, Acinetobacter baumannii, Klebsiella pneumoniae, Bordetella pertussis, MRSA, MRSE, VRE, VISA, Escherichia coli, Hepatitis B Virus (HBV), Hepatitis C Virus (HCV), Herpes Simplex Virus Type 1, Herpes Simplex Virus Type 2, HIV-1, Human Coronavirus (not associated with SARS), Feline Calicivirus, Norovirus, Rotavirus, Influenza A, H3N2 Virus', 1, TRUE, 1, FALSE, 0, TRUE, 1, 'none', 'Eye protection, exam gloves', 'None', 'RTU Liquid', 'http://www.metrex.com/sites/default/files/content/education-file/education-file-upload/CaviCide1%20US%20GHS%20SDS%20(3.23.16).pdf', 'http://www.metrex.com/products/surface-disinfectants/cavicide1', 'http://www.metrex.com/sites/default/files/content/education-file/education-file-upload/cavicide1-technical-bulletin-us-en.pdf', 'https://www3.epa.gov/pesticides/chem_search/ppls/046781-00012-20120419.pdf', 10, 4, 7);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('CaviWipes1', 'Metrex', '46781-13','disinfectantimages/CaviWipes1.jpg', 'quat/alcohol', 'intermed', 'hard', 'Mycobacterium tuberculosis (TB), Staphylococcus aureus, Pseudomonas aeruginosa, Salmonella enterica, Trichophyton mentagrophytes, Candida albicans, Acinetobacter baumannii, Klebsiella pneumoniae, Bordetella pertussis, MRSA, MRSE, VRE, VISA, Escherichia coli, Hepatitis B Virus (HBV),  Hepatitis C Virus (HCV), Herpes Simplex Virus Type 1, Herpes Simplex Virus Type 2, HIV-1, Human Coronavirus (not associated with SARS), Influenza A, H3N2 Virus', 1, FALSE, 0, FALSE, 0, TRUE, 1, 'none', 'Eye protection, exam gloves', 'None', 'RTU Wipes', 'http://www.metrex.com/sites/default/files/content/education-file/education-file-upload/CaviWipes1%20US%20GHS%20SDS%20(3.23.2016).pdf', 'http://www.metrex.com/products/surface-disinfectants/caviwipes1', 'http://www.metrex.com/sites/default/files/content/education-file/education-file-upload/caviwipes1-technical-bulletin-us-en-10-22-2014.pdf', 'https://www3.epa.gov/pesticides/chem_search/ppls/046781-00013-20160519.pdf', 10, 4, 8);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('CaviCide AF', 'Metrex', '1839-225-46781','disinfectantimages/CaviCideAF.jpg', 'quat', 'intermed', 'hard', 'Mycobacterium bovis (TB), Pseudomonas aeruginosa, MRSA, E. coli, Streptococcus pyogenes, Listeria monocytogenes, Yersinia enterocolitica, Corynebacterium ammoniagenes, Salmonella enterica, VRE, Staphylococcus aureus, MRSE, CA-MRSA, Human Coronavirus, SARS-associated Coronavirus, Avian Influenza A virus strain H3N2, Avian Influenza A virus strain H9N2, Influenza A (H1N1) Virus, Paramyxovirus (Mumps), Rhinovirus, Rotavirus, HIV-1, Norovirus, Feline Calicivirus, Rabies Virus', 3, TRUE, 0.5, FALSE, 0, FALSE, 0, 'none', 'Eye protection, exam gloves', 'None', 'RTU Liquid', 'http://www.metrex.com/sites/default/files/content/education-file/education-file-upload/CaviCide%20AF%20GHS%20SDS%20Final.pdf', 'http://www.metrex.com/products/surface-disinfectants/cavicide-af', 'http://www.metrex.com/sites/default/files/content/education-file/education-file-upload/MKT-1172%20CaviCide%20AF%20Technical%20Bulletin_20150929.pdf', 'https://www3.epa.gov/pesticides/chem_search/ppls/001839-00225-20110106.pdf', 8, 7, 7);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Sani-Cloth Bleach Wipes', 'PDI', '9480-8','disinfectantimages/saniclothbleachwipe.png', 'sodium hypochlorite (bleach)', 'high', 'hard', 'Bordetella pertussis, Burkholderia cepacia, Campylobacter jejuni, Escherichia coli, Klebsiella pneumoniae,  Legionella pneumophila, Listeria monocytogenes, Pseudomonas aeruginosa, Salmonella enterica, Serratia marcescens, Staphylococcus aureus, Streptococcus pyogenes, Acinetobacter baumannii, Enterobacter cloacae, Escherichia coli, Klebsiella pneumoniae, CA-MRSA, MRSA, Streptococcus pneumoniae, VISA, VRSA, VRE, Avian Influenza A H5N1 virus, Cytomegalovirus, Herpes simplex virus type 2, Human Coronavirus, Influenza A virus /Hong Kong Strain, Influenza B virus, RSV, Adenovirus type 2, Canine Parvovirus, Hepatitis A virus  (HAV), Norovirus, Poliovirus, Rhinovirus, Rotavirus, Hepatitis B virus (HBV), Hepatitis C virus (HCV) Bovine Diarrhea Virus, HIV-1 (AIDS virus), Aspergillus brasiliensis, Candida albicans, Trichophyton mentagrophytes, Clostridium difficile spores', 1, TRUE, 1, TRUE, 4, TRUE, 4, '1/1/0', 'Eye protection, exam gloves, face mask', 'None', 'RTU Wipes', 'http://pdihc.com/sites/default/files/73bbedd76aa896857c5cd65b507943bc.pdf', 'http://pdihc.com/content/sani-cloth%C2%AE-bleach', '', 'https://www3.epa.gov/pesticides/chem_search/ppls/009480-00008-20130716.pdf', 10, 7, 10);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Sani-Cloth AF3 Wipes', 'PDI', '9480-9','disinfectantimages/saniclothaf3.png', 'quat', 'intermed', 'hard', 'Bordetella bronchiseptica, Bordetella pertussis, Burkholderia cepacia, Campylobacter jejuni, Enterobacter aerogenes,  Escherichia coli, Klebsiella pneumoniae,  Listeria monocytogenes, Proteus vulgaris, Pseudomonas aeruginosa, Salmonella enterica, Serratia marcescens, Shigella dysenteriae, Staphylococcus aureus, Streptococcus pyogenes, Vibrio cholera, Yersinia enterocolitica, Acinetobacter baumannii, CA-MRSA, MRSA,  Streptococcus pneumoniae, VRSA, VRE, Avian Influenza A H5N1 virus, Cytomegalovirus, Herpes simplex virus type 2, Human Coronavirus, Influenza A virus/Hong Kong, Pandemic 2009 H1N1 influenza A virus, Influenza B virus, RSV,  Rotavirus, Hepatitis B virus (HBV), Hepatitis C virus (HCV),  HIV-1 (AIDS virus),', 3, FALSE, 0, FALSE, 0, TRUE, 3, '2/0/0', 'Exam gloves', 'None', 'RTU Wipes', 'http://pdihc.com/sites/default/files/SaniClothAF3SDSEnglish.pdf', 'http://pdihc.com/all-products/sani-cloth%C2%AE-af3', 'http://pdihc.com/sites/default/files/f8b79134a2baab9c20550eab22c1be4a.pdf', '', 8, 4, 10);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Super Sani-Cloth Wipes', 'PDI', '9480-4 ','disinfectantimages/supersanicloth.png', 'quat/alcohol', 'intermed', 'hard', 'Acinetobacter baumannii, Enterobacter cloacae, Escherichia coli (E. coli), Klebsiella pneumoniae, MRSA,  VRE, Bordetella pertussis, Burkholderia cepacia, Campylobacter jejuni, Escherichia coli (E. coli), Pseudomonas aeruginosa, Salmonella enterica, Staphylococcus aureus, Mycobacterium bovis (TB), Herpes Simplex type 2 virus, Human Coronavirus, Influenza A virus/Hong Kong, Pandemic 2009 H1N1 Influenza A virus, Influenza A (H1N1) virus, Vaccinia virus, RSV, Adenovirus, Rhinovirus, Rotavirus, Hepatitis B virus (HBV), Hepatitis C virus (HCV), HIV-1 (AIDS virus), Candida albicans', 2, FALSE, 0, FALSE, 0, FALSE, 0, '2/3/0', 'Eye protection, exam gloves, face mask', 'None', 'RTU Wipes', 'http://pdihc.com/sites/default/files/966b322087d48685dcb3ffa38712b578.pdf', 'http://pdihc.com/content/super-sani-cloth%C2%AE', 'http://pdihc.com/sites/default/files/77fd3798ce1162b368e48dcd1ff80302.pdf', '', 9, 4, 10);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Oxivir TB Liquid', 'Diversey', '70627-56','disinfectantimages/oxivirtb.jpg', 'hydrogen peroxide', 'intermed', 'both', 'Staphylococcus aureus, Salmonella Enterich, Pseudomonas aeruginosa, Acinetobacter baumannii, Escherichia coli, Klebsiella pneumoniae, Shigella dysenteriae, VRE, MRSA, CA-MRSA, Adenovirus, Hepatitis B (HBV), Hepatitis C (HCV), Herpes Simplex virus type 1, Herpes Simplex virus type 2, HIV-1 (AIDS virus), Human Coronavirus, Influenza A Hong Kong, Norovirus, Poliovirus, Rhinovirus, Rotavirus, Avian Influenza A, Mycobacterium bovis (TB), Trichophyton mentagrophytes', 1, TRUE, 1, FALSE, 0, TRUE, 5, '0/0/0', 'None for routine tasks', 'None', 'RTU Liquid', 'https://sds.sealedair.com/private/document.aspx?prd=MS0800255~~PDF~~MTR~~ANGH~~EN~~&_ga=1.209068178.120435454.1467725938', 'https://sealedair.com/diversey-care/diversey-care-products/oxivir-tb', '', 'https://www3.epa.gov/pesticides/chem_search/ppls/070627-00056-20141209.pdf', 10, 10, 7);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Oxivir TB Wipes', 'Diversey', '70627-60','disinfectantimages/oxivirtbwipes.jpg', 'hydrogen peroxide', 'intermed', 'hard', 'Staphylococcus aureus, Acinetobacter baumannii, Klebsiella pneumoniae, Salmonella enterica, Escherichia coli, Shigella dysenteriae, Pseudomonas aeruginosa, VRE, CA-MRSA, MRSA,  Adenovirus ,Herpes Simplex Virus Type 2, Norovirus, Hepatitis B Virus (HBV), HIV-1 (AIDS Virus), Poliovirus, Hepatitis C Virus (HCV), Human Coronavirus, Rhinovirus, Herpes Simplex Virus Type 1 (HSV-1), Influenza A/Hong Kong, Rotavirus, Avian Influenza A (H3N2), Mycobacterium bovis (TB),  Trichophyton mentagrophytes', 1, TRUE, 1, FALSE, 0, TRUE, 10, '0/0/0', 'None for routine tasks', 'None', 'RTU Wipes', 'https://sds.sealedair.com/private/document.aspx?prd=MS0800545~~PDF~~MTR~~ANGH~~EN~~&_ga=1.83184662.120435454.1467725938', 'https://sealedair.com/diversey-care/diversey-care-products/oxivir-tb-wipes', '', 'https://www3.epa.gov/pesticides/chem_search/ppls/070627-00060-20150729.pdf', 10, 10, 7);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Oxivir Five 16 Liquid', 'Diversey', '70627-58','disinfectantimages/oxivirfive16.jpg', 'hydrogen peroxide', 'low', 'hard', 'Pseudomonas aeruginosa, Salmonella enterica, Staphylococcus aureus, Acinetobacter baumannii, Escherichia coli, Klebsiella pneumoniae, Usteria monocytogenes, Shigella dysenteriae, Streptococcus pyogenes, VRE, CA-MRSA, MRSE, MRSA, Streptococcus pneumoniae, Avian Influenza A Virus, Trichophyton mentagrophytes, Adenovirus, Herpes Simplex Virus Type 2, Human Coronavirus,  Influenza Virus Type A2 (Hong Kong), Norovirus, Parainfluenza Virus, Poliovirus, RSV, Rhinovirus, Rotavirus, Vaccinia Virus, Hepatitis B Virus (HBV), Hepatitis C Virus (HCV), HIV-1 (AIDS virus)', 5, TRUE, 5, FALSE, 0, TRUE, 10, '0/0/0', 'None for routine tasks', 'Mix bucket, measure cup or pump, water source', 'Concentrate', 'https://sealedair.com/diversey-care/diversey-care-products/oxivir-five-16-concentrate', 'https://sealedair.com/diversey-care/diversey-care-products/oxivir-five-16-concentrate', '', 'https://www3.epa.gov/pesticides/chem_search/ppls/070627-00058-20101119.pdf', 6, 10, 7);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, 	noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Accel TB Liquid', 'Virox', '74559-1','disinfectantimages/AccelTBLiquid.png', 'hydrogen peroxide', 'intermed', 'both', 'Acinetobacter baumannii, Adenovirus Type 8, Avian Influenza A H3N2, VRE, E. coli, Hepatitis B (HBV), Hepatitis C (HCV), Herpes Simplex Type 1, Herpes Simplex Type 2, HIV-1, Human Coronavirus, Influenza A Hong Kong, Klebsiella pneumoniae, Poliovirus Type 1, Pseudomonas aeruginosa, Rhinovirus, Rotavirus, Salmonella enterica, Staphylococcus aureus, Staphylococcus aureus MRSA', 1, TRUE, 1, FALSE, 0, TRUE, 10, '0/0/0', 'None for routine tasks', 'None', 'RTU Liquid', 'http://unimedcorp.com/MSDS/SDS_AccelTBLiquidDisinfectant.pdf', 'http://viroxhealthcare.com/index_en.php?page=accel-rtu-liquids', '', 'https://www3.epa.gov/pesticides/chem_search/ppls/074559-00001-20151102.pdf', 10, 10, 7);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Accel Concentrate Liquid', 'Virox', '74559-4','disinfectantimages/accelconcentrate.jpg', 'hydrogen peroxide', 'low', 'hard', 'Acinetobacter baumannii, Canine parvovirus, VRE, E. coli, Hepatitis B (HBV), Hepatitis C (HCV), Herpes Simplex Type 2, HIV-1, Human Coronavirus, Influenza A Hong Kong, Klebsiella pneumoniae, Listeria monocytogenes, MRSA, Parainfluenza type 3, Poliovirus Type 1, Pseudomonas aeruginosa, RSV, Rotavirus, Salmonella, Shigella dysenteriae, Staphylococcus aureus, Staphylococcus epidermis, Streptococcus pneumoniae, Streptococcus pyogenes, Vaccinia', 5, TRUE, 5, FALSE, 0, TRUE, 5, '2/0/0', 'Exam gloves', 'Mix bucket, measuring cup/pump, water source', 'Concentrate', 'http://unimedcorp.com/MSDS/sds_Accel(Concentrate).pdf', 'http://viroxhealthcare.com/index_en.php?page=accel-concentrate', '', 'https://www3.epa.gov/pesticides/chem_search/ppls/074559-00004-20160119.pdf', 8, 4, 10);

CREATE TABLE choices (
	id SERIAL PRIMARY KEY NOT NULL,
	areas VARCHAR(30),
	surfaces VARCHAR(30),
	pathogens VARCHAR(30),
	format VARCHAR(30)
	);
	
INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Citrus II Liquid', 'Beaumont', '1839-83-68939','disinfectantimages/citrusII.jpg', 'quat', 'low', 'hard', 'Escherichia coli, Hepatitis A virus (HAV), Hepatitis B virus (HBV), Hepatitis C virus (HCV), MRSA, Salmonella enterica, Mycobacterium bovis (TB), VRE, Trichophyton mentagrophytes, Parvovirus', 10, FALSE, 0, FALSE, 0, TRUE, 10, 'none', 'Exam gloves', 'none', 'RTU Liquid', 'http://www.unimedcorp.com/MSDS/sds_CitrusIIHospitalGermicidalDeodorizingCleaner.pdf', 'http://www.beaumontproducts.com/pc_combined_results.asp?search_cat=searchexact~pcpcm.parent_pc_id~3EE96E2E041C41669CFD9169C142E081&pc_id=3EE96E2E041C41669CFD9169C142E081', '', 'https://www3.epa.gov/pesticides/chem_search/ppls/001839-00083-20140114.pdf', 1, 4, 3);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Peridox RTU Liquid', 'Contec', '8383-13','disinfectantimages/peridox_rtu.jpg', 'hydrogen peroxide/peracetic acid', 'high', 'both', 'Avian influenza virus A (H3N2), Human coronavirus, Adenovirus, Avian influenza virus H5N1, Herpes simplex virus, Type 1 & 2, Human immunodeficiency virus, Type 1 (HIV-1), Influenza A virus (H1N1), Influenza virus, Type A, Influenza virus, Type B, Norovirus, Poliovirus, Type 1, Reovirus,  Respiratory syncytial virus (RSV), Rhinovirus, Rotavirus, Hepatitis B virus,  Mycobacterium bovis (TB), Enterobacter aerogenes, Listeria monocytogenes, Pseudomonas aeruginosa, Salmonella typhimurium, Staphylococcus aureus, Vibrio cholerae, Salmonella enterica, Acinetobacter baumannii,  Campylobacter jejuni, E. coli, Enterococcus faecalis Vancomycin Resistant (VRE), Enterococcus hirae, Haemophilus influenzae, Klebsiella pneumoniae, Legionella pneumophila, Proteus vulgaris, Serratia marcescens, Shigella sonnei, MRSA,  CA-MRSA, Streptococcus Pneumoniae, Streptococcus pyogenes', 2, TRUE, 2, TRUE, 3, TRUE, 1, '2/0/0', 'Eye protection, exam gloves, face mask', 'none', 'RTU Liquid', 'http://www.actiocms.com/VIEW_MSDS/AuthorDisplay_V402/msdsdisplaycode_author_new_MASTER.cfm?edit_msds_id=234527&dbname=production&Hide_Section_Numbers=N&formatcode=7&language=1&noprint_label_fax_email=N', 'http://www.contecinc.com/products/life-sciences/solutions,-disinfectants-and-soaps/all/peridoxrtu(r)-sporicidal-disinfectant', 'http://www.contecinc.com/media/literature/dis011_peridox_rtu_efficacy_data.pdf', 'https://www3.epa.gov/pesticides/chem_search/ppls/088089-00004-20150508.pdf', 9, 4, 10);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Sporicidin', 'Contec', '8383-3','disinfectantimages/sporicidin.jpg', 'phenol/sodium phenate', 'intermed', 'hard', 'Avian Influenza A virus (H5N1), Avian Influenza A virus (H9N2), Cytomegalovirus, Herpes simplex virus, HIV-1 (AIDS virus), Human Coronavirus, Influenza A virus (H1N1 Pandemic Flu), Influenza A virus (H3N2), Norovirus, Parainfluenza type 3 virus, Polio type 1 virus, Vaccinia virus, Acinetobacter baumannii, Escherichia coli (E. coli), MRSA, Pseudomonas aeruginosa, Salmonella enterica, Staphylococcus aureus, Streptococcus pyrogenes, Streptococcus salivarius, Tuberculosis (Mycobacterium Bovis), VRE', 10, TRUE, 5, FALSE, 0, TRUE, 10, '1/1/0', 'Eye protection, exam gloves, face mask', 'none', 'RTU Liquid', 'http://www.actiocms.com/VIEW_MSDS/AuthorDisplay_V402/msdsdisplaycode_author_new_MASTER.cfm?edit_msds_id=229461&dbname=production&Hide_Section_Numbers=N&formatcode=7&language=1&noprint_label_fax_email=N', 'http://www.contecinc.com/products/life-sciences/solutions,-disinfectants-and-soaps/all/sporicidin(r)-disinfectant-solution', 'http://www.contecinc.com/media/literature/spo006_tested%20organisms.pdf', 'https://www3.epa.gov/pesticides/chem_search/ppls/008383-00003-20150112.pdf', 1, 7, 7);

INSERT INTO products (productname, manufacturer, eparegno, image, chemistry, areas, surfaces, bvclaims, bvkill, noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, format, sds, productpage, 	techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Clorox Bleach Concentrate', 'Clorox', '67619-12','disinfectantimages/cloroxbleachconcentrate.png', 'sodium hypochlorite (bleach)', 'high', 'hard', 'Adenovirus Type 2, Cytomegalovirus, Hepatitis A Virus (HAV), Hepatitis B Virus (HBV), Hepatitis C Virus (HCV), Herpes Simplex Virus type 2, Human Coronavirus, Human Immunodeficiency Virus Type 1 (HIV-1), Influenza A Virus, Influenza A (H1N1), Influenza B Virus, Norovirus, Parainfluenza, Poliovirus, RSV, Rhinovirus, Rotavirus, Rubella Virus, Varicella-Zoster Virus, Acinetobacter baumannii, VRE, Escherichia coli, Legionella pneumophila, Pseudomonas aeruginosa, Salmonella enterica, Shigella dysentriae, Staphylococcus aureus, MRSA, CA-MRSA, Streptococcus pneumoniae, Streptococcus pyogenes', 10, TRUE, 5, TRUE, 5, TRUE, 5, '3/0/0', 'Eye protection, exam gloves, face mask', 'Mix bucket, measuring cup, water source', 'Concentrate', 'https://www.thecloroxcompany.com/downloads/msds/cloroxprofessionalproductscloroxcommercialsolutionscloroxliquidssprays/cloroxcommercialsolutionscloroxgermicidalbleach12015-06-12.pdf', 'https://www.cloroxprofessional.com/products/clorox-germicidal-bleach/at-a-glance/', '', 'https://www3.epa.gov/pesticides/chem_search/ppls/067619-00012-20150812.pdf', 1, 7, 7);

INSERT INTO products (productname, manufacturer, eparegno, image, areas, surfaces, format, chemistry, bvclaims, bvkill, noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, productpage, sds, techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Clorox Bleach RTU','Clorox','11346-3','disinfectantimages/cloroxbleachrtuliquid.png','high','hard','RTU Liquid','sodium hypochlorite (bleach)','Avian Influenza A virus, Canine Parvovirus, Feline Panleukopenia virus, Hepatitis A virus (HAV), Hepatitis B virus (HBV), Hepatitis C virus (HCV), Herpes simplex virus (HSV-2), Human Immunodeficiency Virus Type 1 (HIV-1), Influenza A virus, Influenza A virus (H1N1), Norovirus, Poliovirus type 1, Rhinovirus, Rotavirus, Acinetobacter baumannii, Bordetella pertussis, Campylobacter jejuni, Enterobacter aerogenes, Enterobacter cloacae, Enterococcus faecium, VRE, Escherichia coli, Klebsiella pneumoniae, Carbapenum resistant Klebsiella pneumoniae, Proteus mirabilis, Pseudomonas aeruginosa, Salmonella enterica, Serratia marcescens, Staphylococcus aureus, MRSA, VISA, VRSA, Stenotrophomonas maltophilia, Streptococcus pneumoniae, Streptococcus pyogenes',1,TRUE,1,TRUE,5,TRUE,1,'1/0/1','Eye protection, exam gloves, face mask','None','https://www.cloroxprofessional.com/products/clorox-healthcare-bleach-germicidal-cleaners/at-a-glance/','https://www.thecloroxcompany.com/downloads/msds/cloroxhealthcarecloroxhealthcarecloroxhealthcare/cloroxhealthcarebleachgermicidalcleanerjw.pdf','','https://www3.epa.gov/pesticides/chem_search/ppls/011346-00003-20141016.pdf',10,7,10)

INSERT INTO products (productname, manufacturer, eparegno, image, areas, surfaces, format, chemistry, bvclaims, bvkill, noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, productpage, sds, techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Clorox HP Liquid ','Clorox','67619-24','disinfectantimages/cloroxhpliquid.png','intermed','both','RTU Liquid','hydrogen peroxide','Avian Influenza A, Cytomegalovirus, Human Hepatitis B virus, Human Hepatitis C virus, Herpes Simplex virus type 1, Herpes Simplex virus type 2, HIV type 1, Human Coronavirus, Influenza A virus (H1N1), Influenza A virus / Hong Kong, Influenza B virus, Norovirus, RSV, Rhinovirus, Rotavirus, Acinetobacter baumannii, Campylobacter jejeuni, Enterobacter aerogenes, VRE,†Enterococcus faecium, Escherichia coli, Klebsiella pneumoniae, Klebsiella oxytoca, Pseudomonas aeruginosa, Salmonella enterica, Staphylococcus aureus, MRSA, CA-MRSA, Staphylococcus epidermidis, Stenotrophomonas maltophilia, Streptococcus pneumonia, Streptococcus pyogenes',1,TRUE,1,FALSE,0,TRUE,3,'1/0/0','Exam gloves','None','https://www.cloroxprofessional.com/products/clorox-healthcare-hydrogen-peroxide-cleaner-disinfectants/at-a-glance/','https://www.thecloroxcompany.com/downloads/msds/cloroxhealthcarecloroxhealthcarecloroxhealthcare/cloroxhealthcarehydrogenperoxidecleanerdisinfectantjw2015-04-27.pdf','','https://www3.epa.gov/pesticides/chem_search/ppls/067619-00024-20130826.pdf',10,7,10)

INSERT INTO products (productname, manufacturer, eparegno, image, areas, surfaces, format, chemistry,  bvclaims, bvkill, noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, productpage, sds, techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Virasept','Ecolab','1677-226','disinfectantimages/Virasept.jpg','high','hard','RTU Liquid','hy. perox./octanoic acid/ peroxyacetic acid','Pseudomonas aeruginosa, Klebsiella pneumoniae, Staphylococcus aureus, Serratia marcescens, Salmonella enterica, Escherichia coli, MRSA, VISA, Shigella flexneri, VRE, Enterobacter aerogenes, Proteus vulgaris, Acinetobacter baumannii, Clostridium difficile, Mycobacterium bovis, Norovirus, Rhinovirus, Hepatitis B Virus (HBV), Rotavirus, Adenovirus, RSV, Avian Influenza A, Human Coronavirus, Influenza A Virus, HIV-1 (AIDS Virus), Hepatitis B Virus (HBV), Trichophyton mentagrophytes',4,TRUE,4,TRUE,10,TRUE,4,'3/0/0','Eye protection, exam gloves','None','http://www.ecolab.com/product/virasept/','http://portal.ecolab.com/servlet/PdfServlet?sid=913261&cntry=US&langid=en-US&langtype=RFC1766LangCode&locale=en_US&pdfname=VIRASEPT','','https://www3.epa.gov/pesticides/chem_search/ppls/001677-00226-20150202.pdf',7,1,10)

INSERT INTO products (productname, manufacturer, eparegno, image, areas, surfaces, format, chemistry, bvclaims, bvkill, noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, productpage, sds, techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Asepti-HB','Ecolab','61178-2-1677','disinfectantimages/AseptiHB.jpg','intermed','hard','RTU Liquid','quat','Aspergillus niger, Candida albicans, Cryptococcus neoformans, Pseudomonas aeruginosa, Staphylococcus aureus, Streptococcus pneumoniae, VRE, Micrococcus luteus,  Staphylococcus epidermidis, Staphylococcus saprophyticus, Streptococcus haemolyticus, Acinetobacter calcoaceticus, Acinetobacter calcoaceticus, Bordetella bronchiseptica, Brevundiinonas dimunita, Burkholderia cepacia, Enterobacter agglomerans, Enterobacter cloacae, Enterobacter gergoviae, Enterobacter liquefaciens, Escherichia coli, Flavobacterium meningosepticum, Hafnia alvei, Klebsiella oxytoca, Klebsiella pneumoniae, Morganella morganii, Proteus mirabilis, Proteus vulgaris, Pseudomonas fluorescens, Pseudomonas pseudomallei, Pseudomonas putida,  Pseudomonas stutzeri, Serratia marcescens, Sphingomonas paucimobilis, Actinobacillus pleuropneumoniae,  Actinomyces pyogenes, Bacillus cereus, Brevibacterium ammoniagenes, Bordetella bronchiseptica,  Burkholderia pickettii, Campylobacter jejuni, Chryseomonas luteola, Corynebacterium ammoniagenes,  Corynebacterium pseudotuberculosis, Enterobacter aerogenes, Escherichia vulneris, Legionella pneumophila, Listeria monocytogenes, Neisseria gonorrhoeae, Pasteurella haemolytica, Rhodococcus egui, Salmonella schottmuelleri, Salmonella typhi, Shigella dysenteriae, Staphylococcus auricularis, Staphylococcus capitis,  Staphylococcus hominis, Staphylococcus simulans, Stenotrophomonas maltophilia, Streptococcus equi, Streptococcus equi, Streptococcus pyogenes, Streptococcus salivarius, Treponema pallidum, Yersinia enterocolitica, Trichophyton mentagrophytes, Aspergillus candidus, Aspergillus niger, Penicillium chermesinum, Penicillium oxalicum, Penicillium spinulosum, Klebsiella oxytoca, Klebsiella pneumoniae,  MRSA, Staphylococcus epidermidis, Adenovirus, Cytomegalovirus, Echovirus, Hepatitis B Virus (HBV), Herpes Simplex type 1, Herpes Simplex type 2, HIV-1 (AIDS Virus),  Influenza A (H3N2), Influenza B Virus,  Influenza C Virus, Measles Virus, Parainfluenza, Vaccinia Virus, Avian Influenza A',10,FALSE,0,FALSE,0,TRUE,10,'1/0/0','Eye protection, exam gloves','None','http://www.ecolab.com/product/asepti-hb/','http://portal.ecolab.com/servlet/PdfServlet?sid=999149&cntry=US&langid=en-US&langtype=RFC1766LangCode&locale=en_US&pdfname=ASEPTI-HB','','https://www3.epa.gov/pesticides/chem_search/ppls/061178-00002-20110615.pdf',1,7,10)

INSERT INTO products (productname, manufacturer, eparegno, image, areas, surfaces, format, chemistry,  bvclaims, bvkill, noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, productpage, sds, techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('SaniZide Plus','Safetec','1839-83-67161','disinfectantimages/SaniZidePlus.jpg','intermed','hard','RTU Liquid','quat/alcohol','Hepatitis A Virus (HAV), Hepatitis B Virus (HBV), Hepatitis C Virus (HCV),  HIV-1 (AIDS virus), Human Coronavirus, Norovirus, Poliovirus Type 1, SARS Associated Coronavirus, Avian Flu A (Strains H9N2 and H3N2), 2009 H1N1 Influenza A Virus, Staphylococcus aureus, Salmonella (choleraesuis) enterica, Pseudomonas aeruginosa, Escherichia coli (E. coli), Salmonella (typhi) enterica, Streptococcus pyogenes, CA-MRSA, MRSE, VRE, VISA',10,TRUE,0.5,FALSE,0,TRUE,10,'1/0/0','Eye protection, exam gloves','None','http://safetec.com/portfolio_item/sanizide-plus-surface-disinfectant-spray/','http://safetec.com/files/Safetec%20SaniZide%20Plus%20Germicidal%20Solution.pdf','','https://www3.epa.gov/pesticides/chem_search/ppls/001839-00083-20140114.pdf',1,7,3)

INSERT INTO products (productname, manufacturer, eparegno, image, areas, surfaces, format, chemistry, bvclaims, bvkill, noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, productpage, sds, techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Simple Green d-Pro-5','Sunshine Makers Inc.','6836-140-56782','disinfectantimages/simplegreendpro5.png','low','hard','Concentrate','quat','Acinetobacter baumannii, Adenovirus Type 5 & Type 7,  Avian Infectious Bronchitis Virus, Avian Influenza Virus (H3N2) & (H5N1), Brevibacterium ammoniagenes, Canine Distemper Virus, Campylobacter jejuni, Enterobacter aerogenes, Enterococcus faecalis, VRE,  Escherichia coli, Hepatitis B Virus & Hepatitis C Virus, Herpes Simplex Virus Type 1 & Type 2, HIV-1 (AIDS Virus), Human Coronavirus, Influenza Virus Type A, Klebsiella pneumoniae, Legionella pneumophilia, Listeria monocytogenes, Newcastleís Disease Virus, Norovirus, Pseudomonas aeruginosa, Pseudomonas cepacia, Pseudorabies Virus, RSV, SARS Associated Coronavirus, Salmonella enterica, Salmonella schottmuelleri, Salmonella typhi, Serratia marcescens, Shigella dysenteriae, Staphylococcus aureus, CA_MRSA, MRSA, VISA,  Streptococcus pyogenes, Vaccinia Virus, Vibrio cholerae',10,TRUE,10,FALSE,0,TRUE,10,'3/1/0','Eye protection, exam gloves, face mask','None','http://simplegreen.com/industrial/products/d-pro-5/','http://simplegreen.com/downloads/SDS_EN-US_SimpleGreendPro5.pdf','http://simplegreen.com/downloads/TDS_EN-US_SimpleGreendPro5.pdf','https://www3.epa.gov/pesticides/chem_search/ppls/006836-00140-20150625.pdf',1,1,10)

INSERT INTO products (productname, manufacturer, eparegno, image, areas, surfaces, format, chemistry, bvclaims, bvkill, noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, productpage, sds, techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('TbQuat','3M','1839-83-527','disinfectantimages/tbquat.jpg','intermed','hard','RTU Liquid','quat','Corynebacterium ammoniagenes, Enterococcus faecium (VRE), Escherichia coli, Listeria monocytogenes, Pseudomonas aeruginosa, Salmonella enterica, Salmonella (typhi), Staphylococcus aureus, Streptococcus pyogenes, Yersinia enterocolitica, CA-MRSA, MRSA, MRSE,  VISA, Avian Influenza A H3N2, Avian Influenza A H9N2, Bovine Viral Diarrhea Virus (BVDV), Canine Parvovirus, HIV-1 (AIDS virus),  Hepatitis A Virus (HAV), Hepatitis B Virus (HBV), Hepatitis C Virus (HCV), Norovirus, Human Coronavirus, Paramyxovirus (Mumps), Poliovirus Type 1,  Rabies Virus,  Rhinovirus,  Rotavirus, SARS associated Coronavirus ',10,TRUE,0.5,FALSE,0,TRUE,10,'2/0/0','Eye protection, exam gloves','None','http://solutions.3m.com/wps/portal/3M/en_US/Facilities-Care-Cleaning-NA/commercial-cleaning/cleaning-supplies/~/3M-TB-Quat-Disinfectant-Ready-to-Use-Cleaner-Quart-12-case?N=5927805+8703506+3293413977&rt=rud','http://multimedia.3m.com/mws/mediawebserver?mwsId=SSSSSuUn_zu8l00xM8tGN8txmv70k17zHvu9lxtD7SSSSSS--','http://multimedia.3m.com/mws/media/133241O/3mtm-tb-quat-disinfectant-cleaner-ready-to-use.pdf','https://www3.epa.gov/pesticides/chem_search/ppls/001839-00083-20140114.pdf',1,4,7)

INSERT INTO products (productname, manufacturer, eparegno, image, areas, surfaces, format, chemistry, bvclaims, bvkill, noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, productpage, sds, techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Alcavis HDC Bleach WIpes','Angelini Pharma','65787-4','disinfectantimages/alcavisbleachwipe.png','low','hard','RTU Wipes','sodium hypochlorite (bleach)','Staphylococcus aureus, Salmonella enterica, Pseudomonas aeruginosa',10,FALSE,0,FALSE,0,FALSE,0,'3/0/0','Eye protection, exam gloves, face mask','None','http://angelini-us.com/alcavis-beach-wipe-1100/','http://angelini-us.com/wp-content/uploads/2016/04/MS7-Alcavis-Bleach-Wipe-1-100_rev.2.pdf','http://angelini-us.com/wp-content/uploads/2013/03/bleach_wipe_1-100-product1.pdf','https://www3.epa.gov/pesticides/chem_search/ppls/065787-00004-20151123.pdf',1,1,1)

INSERT INTO products (productname, manufacturer, eparegno, image, areas, surfaces, format, chemistry,  bvclaims, bvkill, noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, productpage, sds, techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('Madacide-1','Mada Med Products','1839-83-11703','disinfectantimages/madacide1.jpg','intermed','hard','RTU Liquid','quat/alcohol','Corynebacterium ammoniagenes, Enterococcus faecium (VRE), Escherichia coli, Listeria monocytogenes, Pseudomonas aeruginosa, Salmonella enterica, Salmonella (typhi), Staphylococcus aureus, Streptococcus pyogenes, Yersinia enterocolitica, CA-MRSA, MRSA, MRSE,  VISA, Avian Influenza A H3N2, Avian Influenza A H9N2, Bovine Viral Diarrhea Virus (BVDV), Canine Parvovirus, HIV-1 (AIDS virus),  Hepatitis A Virus (HAV), Hepatitis B Virus (HBV), Hepatitis C Virus (HCV), Norovirus, Human Coronavirus, Paramyxovirus (Mumps), Poliovirus Type 1,  Rabies Virus,  Rhinovirus,  Rotavirus, SARS associated Coronavirus ',10,FALSE,0,FALSE,0,TRUE,10,'3/0/0','Eye protection, exam gloves','None','http://www.madamedical.com/mm5/merchant.mvc?Store_Code=MM&Screen=PROD&Category_Code=DAUC&Product_Code=7008','http://www.madamedical.com/mm5/pdf/literature/msds/MSDS_MadaCide-1.pdf','','https://www3.epa.gov/pesticides/chem_search/ppls/001839-00083-20140114.pdf',1,1,3)

INSERT INTO products (productname, manufacturer, eparegno, image, areas, surfaces, format, chemistry, bvclaims, bvkill, noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, productpage, sds, techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('DisCide Liquid','Palmero','10492-5','disinfectantimages/discideultraliquid.jpg','intermed','hard','RTU Liquid','quat/alcohol','Mycobacterium bovis (TB), Staphylococcus aureus, Pseudomonas aeruginosa, Salmonella enterica, Escherichia coli (E. coli), Avian Influenza A Virus (H3N2), Influenza A Virus (Hong Kong), Herpes Simplex Virus type 2,  Candida albicans, Proteus mirabilis, MRSA, VRE, Hepatitis B virus (HBV), Hepatitis C virus (HCV),  RSV, HIV-1 (AIDS virus), Human Coronavirus, Adenovirus, Pandemic 2009 H1N1 influenza A Virus',1,FALSE,0,FALSE,0,FALSE,0,'1/3/0','Eye protection, exam gloves','None','https://www.palmerohealth.com/collections/infection-control/products/3565g-discide-ultra-gallon','https://cdn.shopify.com/s/files/1/0883/8832/files/SDS150.pdf?4179617012174430006','','https://www3.epa.gov/pesticides/chem_search/ppls/010492-00005-20110715.pdf',10,7,5)

INSERT INTO products (productname, manufacturer, eparegno, image, areas, surfaces, format, chemistry, bvclaims, bvkill, noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, productpage, sds, techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('DisCide Wipes','Palmero','10492-4','disinfectantimages/discidewipes.jpg','intermed','hard','RTU Wipes','quat/alcohol','Mycobacterium bovis (TB), Staphylococcus aureus, Pseudomonas aeruginosa, Salmonella enterica, Escherichia coli (E. coli), Avian Influenza A Virus (H3N2), Influenza A Virus (Hong Kong), Herpes Simplex Virus type 2,  Candida albicans, Proteus mirabilis, MRSA, VRE, Hepatitis B virus (HBV), Hepatitis C virus (HCV), RSV, HIV-1 (AIDS virus), Human Coronavirus, Adenovirus, Pandemic 2009 H1N1 Influenza A Virus',1,FALSE,0,FALSE,0,FALSE,0,'1/3/0','Eye protection, exam gloves','None','https://www.palmerohealth.com/collections/infection-control/products/10dis-discide-ultra-towelettes-1','https://cdn.shopify.com/s/files/1/0883/8832/files/SDS100.pdf?5357765329777253755','','https://www3.epa.gov/pesticides/chem_search/ppls/010492-00004-20110121.pdf',10,7,5)

INSERT INTO products (productname, manufacturer, eparegno, image, areas, surfaces, format, chemistry, bvclaims, bvkill, noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, productpage, sds, techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('OxyCide','Ecolab','1677-237','disinfectantimages/OxyCide.jpg','high','hard','Concentrate','hydrogen peroxide/peroxyacetic acid','Clostridium difficile, Pseudomonas aeruginosa, Salmonella enterica, Staphylococcus aureus, MRSA, CA-MRSA,  VISA, VRE,  MRSE, Streptococcus pneumoniae, Streptococcus pyogenes, Bordetella pertussis,  Escherichia coli, Klebsiella pneumoniae, Acinetobacter baumannii, Proteus mirabilis, HIV-1 (AIDS virus),  Human Coronavirus, Herpes Simplex Type I virus, Herpes Simplex Type II virus, Influenza A virus Hong Kong, RSV, Vaccinia Virus, Norovirus, Rhinovirus, Rotavirus, Adenovirus, Candida albicans, Trichophyton mentagrophytes',3,TRUE,3,TRUE,3,TRUE,10,'1/0/0','Exam gloves','Proprietary dispensing equipment','http://www.ecolab.com/product/oxycide/','http://portal.ecolab.com/servlet/PdfServlet?sid=979252-15&cntry=US&langid=en-US&langtype=RFC1766LangCode&locale=en_US&pdfname=OXYCIDE+DAILY+DISINFECTANT+CLEANER','','https://www3.epa.gov/pesticides/chem_search/ppls/001677-00237-20151218.pdf',8,7,7)

INSERT INTO products (productname, manufacturer, eparegno, image, areas, surfaces, format, chemistry,  bvclaims, bvkill, noroclaim, norokill, cdiffclaim, cdiffkill, fungiclaim, fungikill, hmis, ppe, equipment, productpage, sds, techdocs, epamasterlabel, scorekill, scoresafety, scorepathogens) VALUES ('BruTab6S','Brulin','71847-6-106','disinfectantimages/BruTab6S.png','high','hard','Concentrate','NaDCC','HIV-1 (AIDS virus), Hepatitis B virus (HBV), Hepatitis A virus (HAV), VRE, Trichophyton mentagrophytes, Klebsiella pneumoniae, Staphylococcus epidermidis, Escherichia coli, Staphylococcus aureus, MRSA, Poliovirus, Herpes simplex virus type 1, Norovirus, Avian influenza, Clostridium difficile, Mycobacterium bovis (Tb), Salmonella enterica, Pseudomonas aeruginosa, Influenza A H1N1, Klebsiella pneumoniae, Acinetobacter baumannii ',10,TRUE,4,TRUE,4,FALSE,0,'1/0/0','Eye protection, exam gloves','Mixing bucket and water source','http://brulin.com/productdetails.aspx?pid=262&cid=26','http://brulin.com/cmsassets/file/msds/161021_msd.pdf','http://brulin.com/cmsassets/file/brandsheets/How_NaDCC_Works.pdf','https://www3.epa.gov/pesticides/chem_search/ppls/071847-00006-20160517.pdf',1,7,8)



